import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "MAINT",
  description: "A cosmetic e commerce platform",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> talha/main
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
