import React from "react";
import Header from "./Header";
import Footer from "./Footer"; // Adjust the import path if necessary

const TermsConditions = () => {
  return (
    <div className="pb-4">
      <Header />
      <main className="pt-28">
        <h1 className="text-3xl md:text-5xl font-playfair-display font-normal text-center mb-8">
          Terms & Conditions
        </h1>
        <p className="text-center font-merriweather font-normal text-sm md:text-base text-gray-500 mb-8">
          Effective Date: April 1, 2024
        </p>
        <section className="max-w-4xl mx-auto font-merriweather font-medium md:text-left text-center px-10 md:px-4">
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            General Terms of Use of Website
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            These Website (“Terms“) are published in accordance with the
            provisions of Rule 3(1) of the Information Technology
            (Intermediaries Guidelines) Rules, 2011. These Terms are an
            ‘electronic record’ as contemplated under section 2(t) of the
            Information Technology Act, 2000 and the Rules there under. These
            Terms being an electronic record are generated by a computer system
            and do not require any physical or digital signatures.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            PLEASE READ THESE TERMS AND CONDITIONS (“T&C”) CAREFULLY. BY
            ACCESSING, BROWSING, USING https://mymeant.com OR ANY OTHER WEBSITE,
            MOBILE VERSION OF THE WEBSITE OR MOBILE APPLICATION (THE TOGETHER
            “WEBSITE”) OR AVAILING ANY OF THE PRODUCTS OF ZAYDEN INTERNATIONAL
            (HEREINAFTER REFERRED TO AS “COMPANY” OR “US” OR “WE”) YOU INCLUDING
            THE PERSONS WHO BROWSES OR THE PERSONS WHO ORDERS THE PRODUCT AGREE
            TO BE BOUND BY ALL OF THE T&C MENTIONED HEREUNDER.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            Introduction
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            The website https://mymeant.com ("Website") is operated by ZAYDEN
            INTERNATIONAL, a company incorporated under the Companies Act, 2013
            having its registered office at D-10, HARE KRISHNA ESTATE, NR.
            ASHOPALAV HOTEL, NAROL SARKHEJ HIGHWAY, NAROL, AHMEDABAD, GUJARAT,
            382405. Use of the Website and its services is governed by these
            Terms of Use (“Terms”).
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            The Agreement
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            The use of this website and services on this website provided by,
            Zayden International (hereinafter referred to as "Owner") are
            subject to the following Terms & Conditions (hereinafter the "Terms
            of Service"), all parts and sub-parts of which are specifically
            incorporated by reference here together with the Privacy Policy.
            Following are the Terms of Service governing your use of
            https://mymeant.com (the "Website"), all pages on the Website and
            any services provided by or on this Website ("Services").
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            By using the Website, You warrant that You have read and reviewed
            these Terms of Service and that You agree to be bound by it. If You
            do not agree to be bound by these Terms of Service, please leave the
            Website immediately. The Owner only agrees to provide use of this
            Website and Services to You if You accept these Terms of Service.
            Further, based on the Services obtained by a User, additional terms
            and conditions in respect of the specific Services may apply, which
            shall be deemed an agreement between the Users and the Owner.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            These Terms could be changed, altered, edited, amended, modified,
            reviewed, revised or substituted by Zayden International at any time
            with or without prior notice and users are requested to read the
            Terms before using or accessing the Website.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            User Eligibility, Account, Passwords, and Security
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            The users who can legally enter into binding contracts as per the
            Indian Contract Act, 1872, which means you must be 18 (Eighteen)
            years of age to use this Website, purchases or any Services
            contained herein. By using this Website, You represent and warrant
            that You are at least 18 years of age and may legally agree to these
            Terms of Service. If you are below the age of 18 years, your parents
            or legal guardians can transact on your behalf if they are
            registered users of this website. You are prohibited from purchasing
            any material which is for adult consumption, the sale or purchase of
            which to/by minors are strictly prohibited. The Owner assumes no
            responsibility or liability for any misrepresentation of Your age on
            this website.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            As a user of the Website or Services, you may be asked to register
            with Us. When You do so, you will choose a user identifier, which
            may be your email address, basic details or another term, as well as
            a password. You may also provide personal information, including,
            but not limited to, your name, phone number, address etc. You are
            responsible for ensuring the accuracy of this information. This
            identifying information will enable you to use the Website and
            Services. You must not share such identifying information with any
            third party and if you discover that your identifying information
            has been compromised, you agree to notify us immediately in writing.
            An email notification will suffice. You are responsible for
            maintaining the safety and security of your identifying information
            as well as keeping us apprised of any changes to your identifying
            information. The billing information you provide us, including
            credit card, billing address and other payment information, is
            subject to the same confidentiality and accuracy requirements as the
            rest of your identifying information. Providing false or inaccurate
            information or using the Website or Services to further fraud or
            unlawful activity is grounds for immediate termination of these
            Terms of Service and also legal action. The Owner reserves the right
            to refuse service, terminate accounts, or remove or edit content in
            its sole discretion.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            License to Use Website
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            The Owner may provide You with certain information as a result of
            Your use of the Website or Services. Such information may include
            but is not limited to, documentation, data or information developed
            by the Owner, and other materials which may assist in Your use of
            the Website or Services (“Owner Materials”). Subject to these Terms
            of Service, the Owner grants You a non-exclusive, limited,
            non-transferable and revocable license to use the Owner Materials
            solely in connection with Your use of the Website and Services. The
            Owner Materials may not be used for any other purpose and this
            license terminates upon Your cessation of use of the Website or
            Services or at the termination of these Terms of Service.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            You agree not to collect the contact information of other Users from
            the Website or download or copy any information by means of
            unsolicited access so as to communicate directly with them or for
            any reason whatsoever. Any unauthorized use by you shall terminate
            the permission or license granted to you by the Website and You
            agree that you shall not bypass any measures used by the Owner to
            prevent or restrict access to the Website.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            Reverse Engineering & Security
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            You agree not to undertake any of the following actions:
          </p>
          <ul className="list-disc pl-8 mb-8">
            <li>
              Reverse engineer, or attempt to reverse engineer or disassemble
              any code or software from or on the Website or Services;
            </li>
            <br />
            <li>
              Violate the security of the Website or Services through any
              unauthorized access, circumvention of encryption or other security
              tools, data mining or interference to any host, user or network.
              The Owner does not accept responsibility for the security of Your
              account or content. You agree that Your use of the Website or
              Services is at Your own risk.
            </li>
          </ul>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            INTELLECTUAL PROPERIETARY RIGHTS
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            User acknowledges that the website contains content, including but
            not limited to graphics, UX/UI, VX, logos, typefaces, text, images,
            icons, audio, video and software, and other material (collective
            Content) that is protected by copyrights, trademarks, trade secrets,
            or other proprietary rights, and that these rights are valid and
            protected in all forms, media and technologies existing now or
            hereinafter developed. You agree that the Website and all Services
            provided by the Owner are the property of the Owner, including all
            copyrights, trademarks, trade secrets, patents, and other
            intellectual property ("Owner IP"). You agree that the Owner owns
            all rights, title, and interest in and to the Owner IP and that You
            will not use the Owner IP for any unlawful or infringing purpose.
            You agree not to reproduce or distribute the Owner IP in any way,
            including electronically or via registration of any new trademarks,
            trade names, service marks or Uniform Resource Locators (URLs),
            without express written permission from the Owner. Any other use,
            including the reproduction, modification, distribution,
            transmission, republication, display, or performance of the Content
            of this website is strictly prohibited.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            PAYMENT & FEES
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            Payments for the products available on Site and app may be made
            through the mentioned methods: Credit Cards, Debit Cards, UPI, Net
            Banking, Wallets, e-Gift cards, and reward points (if applicable).
            Online payments are instant payment options and recommended to
            ensure faster processing of your order. Cash On Delivery (COD)
            option is not available. All orders must be prepaid through net
            banking or UPI. All online payments are handled by authorized
            Payment Gateways considering transaction security measures mandated
            by the RBI and other regulatory authorities. Zayden International is
            not responsible for any breach of information, or inappropriate
            transactions. We reserve the right to refuse service or refuse to
            sell the products on the Website at our sole discretion to anyone
            for any reason at any time.
          </p>

          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            LIMITATION OF LIABILITY
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            You agree not to use the Website or Services for any unlawful
            purpose or any purpose prohibited under this clause. You agree not
            to use the Website or Services in any way that could damage the
            Website, Services or general business of the Owner. User agrees that
            use of this website is at User s sole risk. Neither Zayden
            International, nor its affiliates, nor any of their respective
            partners, officers, directors, employees, agents, third-party
            content providers, merchants, sponsors, licensors or the like
            (collectively, Providers), warrant that this website will be
            uninterrupted or error-free; nor do they make any warranty as to the
            results that may be obtained from the use of this website.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            This website is operated by ZAYDEN INTERNATIONAL on an as is and as
            available basis. ZAYDEN INTERNATIONAL makes no representations or
            warranties of any kind, express or implied, as to the operations of
            the website, the content, information, data or products, included on
            this website to the full extent permissible by the Law.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            ZAYDEN INTERNATIONAL disclaims all the warranties, express or
            implied, including but not limited to, implied warranties of
            merchantability and fitness for a particular purpose. The Owner may
            sell goods or services or allow third parties to sell goods or
            services on the Website. The Owner undertakes to be as accurate as
            possible with all information regarding the goods and services,
            including product descriptions and images. However, the Owner does
            not guarantee the accuracy or reliability of any product information
            and You acknowledge and agree that You purchase such products at
            Your own risk.
          </p>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            Under no circumstances shall ZAYDEN INTERNATIONAL or any other party
            involved in creating, producing, or distributing this website be
            liable for any direct, indirect, incidental, special, or
            consequential damages that result from the use of or inability to
            use this website, including but not limited to reliance by a User on
            any information obtained from ZAYDEN INTERNATIONAL or that result
            from mistakes, omissions, interruptions, deletion of files or email,
            errors, defects, viruses, delays in operation or transmission, or
            any failure of performance, whether or not resulting from
            communications failure, theft, destruction, or unauthorized access
            to ZAYDEN INTERNATIONAL S records, data, programs, or services. User
            hereby acknowledges that these disclaimers and limitation on
            liability shall apply to all content, merchandise, and services
            available through this website. In states that do not allow the
            exclusion of limitation or limitation of liability for consequential
            or incidental damages, User agrees that liability in such states
            shall be limited to the fullest extent permitted by applicable law.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            SHIPPING/DELIVERY POLICY
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            Once our system processes your order, your products are thoroughly
            inspected to ensure they are in perfect condition. After passing the
            final round of quality checks, they are carefully packed and handed
            over to our trusted delivery partner. Our delivery partners will
            bring the package to you as soon as possible. If they are unable to
            reach your provided address or deliver at a suitable time, they will
            contact you to resolve the issue. All the confirmed orders are
            usually shipped within 3-4 business working days (except Sundays and
            public holidays). Once shipped, they ll be delivered to you within
            5-7 working days (except Sundays and public holidays). While we
            strive to avoid delays, during Mega Sale events, dispatches may be
            delayed due to increased volumes. After placing your order, you will
            receive a confirmation message on your registered email and phone
            number. You check the status of your package through the Tracking ID
            in the Confirmation email. When purchasing any product/ physical
            good, You agree to provide us with a valid email, phone number and
            shipping address, as well as valid billing information. Estimated
            delivery time may change due to the customers geographical location,
            shipping destination, product availability, and courier partners
            delivery time & location. A standard shipping charge is applied to
            all orders. We are currently not accepting Cash On Delivery (COD)
            orders. In case of one or more defective products in your order,
            please register a single complaint as the return/replacement will be
            arranged only once. We advise the customers not to accept any
            tampered or damaged packages.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            APPLICABLE LAW AND JURISDICTION
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            These Terms of Use are governed by and to be interpreted in
            accordance with laws of India, without regard to the choice or
            conflicts of law provisions of any jurisdiction. You agree, in the
            event of any dispute arising in relation to these Terms of Use or
            any dispute arising in relation to the Zayden International whether
            in contract or tort or otherwise, to submit to the jurisdiction of
            the courts located at Ahmedabad, Gujarat, India for the resolution
            of all such disputes.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            GRIEVANCE OFFICER
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            In accordance with the applicable law, any grievances which you may
            have with respect to the information shared by you with us hereunder
            and its treatment or any grievance related to Services being availed
            hereunder, may be directed by you to such grievance officer at the
            below mentioned details:
          </p>
          <h2 className="text-2xl font-bold mt-8">Contact Information</h2>
          <p className="mt-4 mb-8 ">
            Customer Care: +91 9104604108
            <br />
            Email Address: meantconnect@gmail.com
            <br />
            Registered Office: D-10, Hare Krishna Estate, Nr. Asopalav Hotel,
            Narol Sarkhej Highway, Narol, Ahmedabad, Gujarat – 382405
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            FORCE MAJEURE
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            We will not be held responsible for any delay or failure to comply
            with its obligations if the delay or failure arises from any cause
            which is beyond our reasonable control or unforeseeable reasons.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            SEVERABILITY
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            If any provision of these Terms of Use is held by a court of
            competent jurisdiction to be unenforceable under applicable law,
            then such provision will be excluded from these Terms of Use and the
            remainder of these Terms of Use will be interpreted as if such
            provision were so excluded and will be enforceable in accordance
            with its terms; provided however that, in such event, these Terms of
            Use will be interpreted so as to give effect, to the greatest extent
            consistent with and permitted by applicable law, to the meaning and
            intention of the excluded provision as determined by such court of
            competent jurisdiction.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            AMENDMENT
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            These Terms of Use are subject to amendments and modifications and
            may be updated from time to time, without any advance notice. You
            are requested to regularly review the Terms of Use as available on
            Insight Cosmetics. Your relationship with Zayden International will
            be governed by the most current version of these Terms of Use, as
            published on mymeant.com .
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            COMMUNICATION
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            You understand that each time uses the Website in any manner, you
            agree to these Terms. By agreeing to these Terms, you acknowledge
            that you are interested in availing and purchasing the products or
            Services that you have selected and consent to receive
            communications via phone or electronic records from the Website
            including e-mail, texts, WhatsApp messages telling you about
            products, offers and services offered by the Website (or its
            affiliates and partners) and understanding your requirements
            Communication can also be by posting any notices on the Website. You
            agree that the communications sent to You by the Website shall not
            be construed as spam or bulk under any law prevailing in any country
            where such communication is received.
          </p>
          <h2 className="text-xl md:text-2xl font-merriweather font-bold mb-4">
            MISCELLANEOUS
          </h2>
          <p className="text-base text-gray-500 md:text-lg font-poppins font-medium leading-relaxed mb-8">
            In addition to these Terms of Sale, you will also ensure that you
            are in compliance with the terms and conditions of the third
            parties, such as bank offers terms and conditions, brand promotional
            offers, whose links, if any, are contained/embedded in the Terms of
            Use. The images of the items on the website are for illustrative
            purposes only. Although we have made every effort to display the
            colours accurately, we cannot guarantee that your computers or
            mobiles or tablets display of the colours accurately reflects the
            colour of the actual items. Your items may vary slightly from those
            images. All sizes and measurements of items are approximate;
            however, we do make every effort to ensure they are as accurate as
            possible. We take all reasonable care to ensure that all details,
            descriptions and prices of items are as accurate as possible. These
            Terms and Conditions supersede all previous oral and written terms
            and conditions (if any) communicated to you by us, for the before or
            after purchase of Product.
          </p>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default TermsConditions;
